# Generated by Django 2.0.7 on 2019-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190319_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='birth_date',
            field=models.DateField(verbose_name='Birthday (mm/dd/yy)'),
        ),
    ]
