# Generated by Django 2.0.7 on 2019-03-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190319_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_date',
            new_name='birth_date',
        ),
    ]
